## Based on work from [Chechik et al., 1998.](https://www-mitpressjournals-org.proxy.lib.duke.edu/doi/pdf/10.1162/089976698300017124)

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import copy

In [2]:
M = 20 #number of memories
N = 150 #number of neurons
timesteps = 2 #number of timesteps for the simulation


#creating patterns
patterns = np.empty(shape = (M, N))
for m in range(M):
    patterns[m] = np.random.choice([-1, 1], N)

In [3]:
#creating the initial connectivity matrix based on a sum of the patterns - THIS SEEMS TO BE THE BOTTLENECK
connectivity = np.zeros(shape = (N, N))
for m in range(M):
    connectivity += np.outer(patterns[m], patterns[m].T)
for i in range(N):
    connectivity[i][i] = 0

Wij = connectivity / np.sqrt(M)
z = Wij.copy()
t = 1

In [6]:
counts = np.unique(Wij, return_counts = True)
counts

(array([-4.02492236, -3.57770876, -3.13049517, -2.68328157, -2.23606798,
        -1.78885438, -1.34164079, -0.89442719, -0.4472136 ,  0.        ,
         0.4472136 ,  0.89442719,  1.34164079,  1.78885438,  2.23606798,
         2.68328157,  3.13049517,  3.57770876]),
 array([   4,    4,   32,   80,  336,  844, 1678, 2728, 3606, 4224, 3450,
        2638, 1584,  836,  326,   94,   34,    2], dtype=int64))

In [8]:
zeros = counts[1][counts[0]==0]
zeros

array([4224], dtype=int64)

In [ ]:
## min val deletion
for i in range(len(z)):
    for j in range(len(z)):
        if np.abs(z[i][j]) > t:
            z[i][j] = z[i][j]
        elif z[i][j] == t:
            z[i][j] = 0
        else:
            z[i][j] = 0

In [ ]:
#set the connectivity matrix to the modified/deleted synaptic values
Wij = z.copy()